#!/usr/bin/env python3
"""Reads data.txt and generates a Python script with an octant LUT array."""

import os

script_dir = os.path.dirname(os.path.abspath(__file__))
data_path = os.path.join(script_dir, "data.txt")
output_path = os.path.join(script_dir, "octant_lut.py")

entries = {}
with open(data_path, encoding="utf-8") as f:
    for i, line in enumerate(f):
        char = line.rstrip("\n")
        entries[i] = char

escaped_chars = [entries.get(i, "").encode("unicode_escape").decode("ascii") for i in range(256)]
max_width = max(len(f'"{e}"') for e in escaped_chars)

lines = ["# Auto-generated by generate_lut.py — do not edit by hand.", "# Maps 8-bit octant bitmask (0–255) to the corresponding Unicode character.", "OCTANT_LUT = ["]
for i, escaped in enumerate(escaped_chars):
    comma = "," if i < 255 else ""
    entry = f'"{escaped}"{comma}'
    lines.append(f'    {entry:<{max_width + 1}}  # {i:3d} ({i:08b})')
lines.append("]")
lines.append("")
lines.append("# Bitmasks for each cell in the 2×4 octant grid (x=column 0–1, y=row 0–3).")
lines.append("# Use bitwise-OR to combine, then index into OCTANT_LUT.")
for y in range(4):
    for x in range(2):
        bit = y * 2 + x
        lines.append(f"CELL_{x}_{y} = 0b{(1 << bit):08b}")
lines.append("")

with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Written {len(entries)} entries to {output_path}")
